/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMDOMStringList;

[scriptable, builtinclass, uuid(39bb7d76-d44b-457d-a00e-d87653a65587)]
interface nsIDOMMozMmsMessage : nsISupports
{
  /**
   * |type| is always "mms".
   */
  readonly attribute DOMString type;

  readonly attribute long      id;

  readonly attribute unsigned long long threadId;

  /**
   * Should be "not-downloaded", "received", "sending", "sent" or "error".
   */
  readonly attribute DOMString delivery;

  readonly attribute nsIDOMDOMStringList deliveryStatus;

  readonly attribute DOMString sender;

  readonly attribute nsIDOMDOMStringList receivers;

  [implicit_jscontext]
  readonly attribute jsval     timestamp;      // Date object

  readonly attribute boolean   read;
  readonly attribute DOMString subject;
  readonly attribute DOMString smil;

  [implicit_jscontext]
  readonly attribute jsval     attachments;    // nsIDOMMozMmsAttachment[]

  [implicit_jscontext]
  readonly attribute jsval     expiryDate;     // Date object
                                               // Expiry date for an MMS to be
                                               // manually downloaded.
};
