/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

// Empty interface for type casting.
[scriptable, builtinclass, uuid(19699aaf-2fd0-46a4-8c26-2dfe17749c19)]
interface nsIMmsMessage : nsISupports
{
};

// Empty interface for type casting.
[scriptable, builtinclass, uuid(7543c805-9c6f-430d-9638-9121b870a141)]
interface nsISmsMessage : nsISupports
{
};

// Empty interface for type casting.
[scriptable, builtinclass, uuid(51fe41f8-8913-476a-99d6-ff521b22218c)]
interface nsIMobileMessageThread : nsISupports
{
};
