/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIMobileMessageCallback;

%{C++
#define SMS_SERVICE_CID { 0xbada3cb8, 0xa568, 0x4dff, { 0xb5, 0x43, 0x52, 0xbb, 0xb3, 0x14, 0x31, 0x21 } }
#define SMS_SERVICE_CONTRACTID "@mozilla.org/sms/smsservice;1"
%}

[scriptable, uuid(c46b44db-fa5c-4a39-a51d-f4aa6b9d4384)]
interface nsISmsService : nsISupports
{
  readonly attribute unsigned long defaultServiceId;

  void getSegmentInfoForText(in DOMString text,
                             in nsIMobileMessageCallback request);

  void send(in unsigned long serviceId,
            in DOMString number,
            in DOMString message,
            in boolean silent,
            in nsIMobileMessageCallback request);

  void addSilentNumber(in DOMString number);
  void removeSilentNumber(in DOMString number);

  void getSmscAddress(in unsigned long serviceId,
                      in nsIMobileMessageCallback request);
};

%{C++
template<typename T> struct already_AddRefed;

already_AddRefed<nsISmsService>
NS_CreateSmsService();
%}
