/*
 * Generated by gdbus-codegen 2.38.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gdbusmodem.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.ofono.Modem
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:OfonoGDBusModem
 * @title: OfonoGDBusModem
 * @short_description: Generated C code for the org.ofono.Modem D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.ofono.Modem ---- */

static const _ExtendedGDBusArgInfo _ofono_gdbus_modem_method_info_get_properties_OUT_ARG_properties =
{
  {
    -1,
    (gchar *) "properties",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_modem_method_info_get_properties_OUT_ARG_pointers[] =
{
  &_ofono_gdbus_modem_method_info_get_properties_OUT_ARG_properties,
  NULL
};

static const _ExtendedGDBusMethodInfo _ofono_gdbus_modem_method_info_get_properties =
{
  {
    -1,
    (gchar *) "GetProperties",
    NULL,
    (GDBusArgInfo **) &_ofono_gdbus_modem_method_info_get_properties_OUT_ARG_pointers,
    NULL
  },
  "handle-get-properties",
  FALSE
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_modem_method_info_set_property_IN_ARG_property =
{
  {
    -1,
    (gchar *) "property",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_modem_method_info_set_property_IN_ARG_value =
{
  {
    -1,
    (gchar *) "value",
    (gchar *) "v",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_modem_method_info_set_property_IN_ARG_pointers[] =
{
  &_ofono_gdbus_modem_method_info_set_property_IN_ARG_property,
  &_ofono_gdbus_modem_method_info_set_property_IN_ARG_value,
  NULL
};

static const _ExtendedGDBusMethodInfo _ofono_gdbus_modem_method_info_set_property =
{
  {
    -1,
    (gchar *) "SetProperty",
    (GDBusArgInfo **) &_ofono_gdbus_modem_method_info_set_property_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-property",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _ofono_gdbus_modem_method_info_pointers[] =
{
  &_ofono_gdbus_modem_method_info_get_properties,
  &_ofono_gdbus_modem_method_info_set_property,
  NULL
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_modem_signal_info_property_changed_ARG_name =
{
  {
    -1,
    (gchar *) "name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_modem_signal_info_property_changed_ARG_value =
{
  {
    -1,
    (gchar *) "value",
    (gchar *) "v",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_modem_signal_info_property_changed_ARG_pointers[] =
{
  &_ofono_gdbus_modem_signal_info_property_changed_ARG_name,
  &_ofono_gdbus_modem_signal_info_property_changed_ARG_value,
  NULL
};

static const _ExtendedGDBusSignalInfo _ofono_gdbus_modem_signal_info_property_changed =
{
  {
    -1,
    (gchar *) "PropertyChanged",
    (GDBusArgInfo **) &_ofono_gdbus_modem_signal_info_property_changed_ARG_pointers,
    NULL
  },
  "property-changed"
};

static const _ExtendedGDBusSignalInfo * const _ofono_gdbus_modem_signal_info_pointers[] =
{
  &_ofono_gdbus_modem_signal_info_property_changed,
  NULL
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_powered =
{
  {
    -1,
    (gchar *) "Powered",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "powered",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_online =
{
  {
    -1,
    (gchar *) "Online",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "online",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_lockdown =
{
  {
    -1,
    (gchar *) "Lockdown",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "lockdown",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_emergency =
{
  {
    -1,
    (gchar *) "Emergency",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "emergency",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_name =
{
  {
    -1,
    (gchar *) "Name",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "name",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_manufacturer =
{
  {
    -1,
    (gchar *) "Manufacturer",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "manufacturer",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_model =
{
  {
    -1,
    (gchar *) "Model",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "model",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_revision =
{
  {
    -1,
    (gchar *) "Revision",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "revision",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_serial =
{
  {
    -1,
    (gchar *) "Serial",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "serial",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_features =
{
  {
    -1,
    (gchar *) "Features",
    (gchar *) "as",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "features",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_interfaces =
{
  {
    -1,
    (gchar *) "Interfaces",
    (gchar *) "as",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "interfaces",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _ofono_gdbus_modem_property_info_type_ =
{
  {
    -1,
    (gchar *) "Type",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "type",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _ofono_gdbus_modem_property_info_pointers[] =
{
  &_ofono_gdbus_modem_property_info_powered,
  &_ofono_gdbus_modem_property_info_online,
  &_ofono_gdbus_modem_property_info_lockdown,
  &_ofono_gdbus_modem_property_info_emergency,
  &_ofono_gdbus_modem_property_info_name,
  &_ofono_gdbus_modem_property_info_manufacturer,
  &_ofono_gdbus_modem_property_info_model,
  &_ofono_gdbus_modem_property_info_revision,
  &_ofono_gdbus_modem_property_info_serial,
  &_ofono_gdbus_modem_property_info_features,
  &_ofono_gdbus_modem_property_info_interfaces,
  &_ofono_gdbus_modem_property_info_type_,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _ofono_gdbus_modem_interface_info =
{
  {
    -1,
    (gchar *) "org.ofono.Modem",
    (GDBusMethodInfo **) &_ofono_gdbus_modem_method_info_pointers,
    (GDBusSignalInfo **) &_ofono_gdbus_modem_signal_info_pointers,
    (GDBusPropertyInfo **) &_ofono_gdbus_modem_property_info_pointers,
    NULL
  },
  "modem",
};


/**
 * ofono_gdbus_modem_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
ofono_gdbus_modem_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct;
}

/**
 * ofono_gdbus_modem_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #OfonoGDBusModem interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
ofono_gdbus_modem_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "powered");
  g_object_class_override_property (klass, property_id_begin++, "online");
  g_object_class_override_property (klass, property_id_begin++, "lockdown");
  g_object_class_override_property (klass, property_id_begin++, "emergency");
  g_object_class_override_property (klass, property_id_begin++, "name");
  g_object_class_override_property (klass, property_id_begin++, "manufacturer");
  g_object_class_override_property (klass, property_id_begin++, "model");
  g_object_class_override_property (klass, property_id_begin++, "revision");
  g_object_class_override_property (klass, property_id_begin++, "serial");
  g_object_class_override_property (klass, property_id_begin++, "features");
  g_object_class_override_property (klass, property_id_begin++, "interfaces");
  g_object_class_override_property (klass, property_id_begin++, "type");
  return property_id_begin - 1;
}



/**
 * OfonoGDBusModem:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link>.
 */

/**
 * OfonoGDBusModemIface:
 * @parent_iface: The parent interface.
 * @handle_get_properties: Handler for the #OfonoGDBusModem::handle-get-properties signal.
 * @handle_set_property: Handler for the #OfonoGDBusModem::handle-set-property signal.
 * @get_emergency: Getter for the #OfonoGDBusModem:emergency property.
 * @get_features: Getter for the #OfonoGDBusModem:features property.
 * @get_interfaces: Getter for the #OfonoGDBusModem:interfaces property.
 * @get_lockdown: Getter for the #OfonoGDBusModem:lockdown property.
 * @get_manufacturer: Getter for the #OfonoGDBusModem:manufacturer property.
 * @get_model: Getter for the #OfonoGDBusModem:model property.
 * @get_name: Getter for the #OfonoGDBusModem:name property.
 * @get_online: Getter for the #OfonoGDBusModem:online property.
 * @get_powered: Getter for the #OfonoGDBusModem:powered property.
 * @get_revision: Getter for the #OfonoGDBusModem:revision property.
 * @get_serial: Getter for the #OfonoGDBusModem:serial property.
 * @get_type_: Getter for the #OfonoGDBusModem:type property.
 * @property_changed: Handler for the #OfonoGDBusModem::property-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link>.
 */

typedef OfonoGDBusModemIface OfonoGDBusModemInterface;
G_DEFINE_INTERFACE (OfonoGDBusModem, ofono_gdbus_modem, G_TYPE_OBJECT);

static void
ofono_gdbus_modem_default_init (OfonoGDBusModemIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * OfonoGDBusModem::handle-get-properties:
   * @object: A #OfonoGDBusModem.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ofono-Modem.GetProperties">GetProperties()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ofono_gdbus_modem_complete_get_properties() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-properties",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusModemIface, handle_get_properties),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * OfonoGDBusModem::handle-set-property:
   * @object: A #OfonoGDBusModem.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_property: Argument passed by remote caller.
   * @arg_value: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ofono-Modem.SetProperty">SetProperty()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ofono_gdbus_modem_complete_set_property() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-property",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusModemIface, handle_set_property),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_VARIANT);

  /* GObject signals for received D-Bus signals: */
  /**
   * OfonoGDBusModem::property-changed:
   * @object: A #OfonoGDBusModem.
   * @arg_name: Argument.
   * @arg_value: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ofono-Modem.PropertyChanged">"PropertyChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("property-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusModemIface, property_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_VARIANT);

  /* GObject properties for D-Bus properties: */
  /**
   * OfonoGDBusModem:powered:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Powered">"Powered"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("powered", "Powered", "Powered", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:online:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Online">"Online"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("online", "Online", "Online", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:lockdown:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Lockdown">"Lockdown"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("lockdown", "Lockdown", "Lockdown", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:emergency:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Emergency">"Emergency"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("emergency", "Emergency", "Emergency", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:name:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Name">"Name"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("name", "Name", "Name", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:manufacturer:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Manufacturer">"Manufacturer"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("manufacturer", "Manufacturer", "Manufacturer", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:model:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Model">"Model"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("model", "Model", "Model", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:revision:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Revision">"Revision"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("revision", "Revision", "Revision", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:serial:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Serial">"Serial"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("serial", "Serial", "Serial", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:features:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Features">"Features"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("features", "Features", "Features", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:interfaces:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Interfaces">"Interfaces"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("interfaces", "Interfaces", "Interfaces", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * OfonoGDBusModem:type:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-ofono-Modem.Type">"Type"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("type", "Type", "Type", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * ofono_gdbus_modem_get_powered: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Powered">"Powered"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
ofono_gdbus_modem_get_powered (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_powered (object);
}

/**
 * ofono_gdbus_modem_set_powered: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Powered">"Powered"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
ofono_gdbus_modem_set_powered (OfonoGDBusModem *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "powered", value, NULL);
}

/**
 * ofono_gdbus_modem_get_online: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Online">"Online"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
ofono_gdbus_modem_get_online (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_online (object);
}

/**
 * ofono_gdbus_modem_set_online: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Online">"Online"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
ofono_gdbus_modem_set_online (OfonoGDBusModem *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "online", value, NULL);
}

/**
 * ofono_gdbus_modem_get_lockdown: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Lockdown">"Lockdown"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
ofono_gdbus_modem_get_lockdown (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_lockdown (object);
}

/**
 * ofono_gdbus_modem_set_lockdown: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Lockdown">"Lockdown"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
ofono_gdbus_modem_set_lockdown (OfonoGDBusModem *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "lockdown", value, NULL);
}

/**
 * ofono_gdbus_modem_get_emergency: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Emergency">"Emergency"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
ofono_gdbus_modem_get_emergency (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_emergency (object);
}

/**
 * ofono_gdbus_modem_set_emergency: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Emergency">"Emergency"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
ofono_gdbus_modem_set_emergency (OfonoGDBusModem *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "emergency", value, NULL);
}

/**
 * ofono_gdbus_modem_get_name: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Name">"Name"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_name() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_name (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_name (object);
}

/**
 * ofono_gdbus_modem_dup_name: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Name">"Name"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_name (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "name", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_name: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Name">"Name"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_name (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "name", value, NULL);
}

/**
 * ofono_gdbus_modem_get_manufacturer: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Manufacturer">"Manufacturer"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_manufacturer() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_manufacturer (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_manufacturer (object);
}

/**
 * ofono_gdbus_modem_dup_manufacturer: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Manufacturer">"Manufacturer"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_manufacturer (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "manufacturer", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_manufacturer: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Manufacturer">"Manufacturer"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_manufacturer (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "manufacturer", value, NULL);
}

/**
 * ofono_gdbus_modem_get_model: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Model">"Model"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_model() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_model (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_model (object);
}

/**
 * ofono_gdbus_modem_dup_model: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Model">"Model"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_model (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "model", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_model: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Model">"Model"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_model (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "model", value, NULL);
}

/**
 * ofono_gdbus_modem_get_revision: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Revision">"Revision"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_revision() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_revision (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_revision (object);
}

/**
 * ofono_gdbus_modem_dup_revision: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Revision">"Revision"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_revision (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "revision", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_revision: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Revision">"Revision"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_revision (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "revision", value, NULL);
}

/**
 * ofono_gdbus_modem_get_serial: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Serial">"Serial"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_serial() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_serial (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_serial (object);
}

/**
 * ofono_gdbus_modem_dup_serial: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Serial">"Serial"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_serial (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "serial", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_serial: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Serial">"Serial"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_serial (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "serial", value, NULL);
}

/**
 * ofono_gdbus_modem_get_features: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Features">"Features"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_features() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
ofono_gdbus_modem_get_features (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_features (object);
}

/**
 * ofono_gdbus_modem_dup_features: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Features">"Features"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
ofono_gdbus_modem_dup_features (OfonoGDBusModem *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "features", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_features: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Features">"Features"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_features (OfonoGDBusModem *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "features", value, NULL);
}

/**
 * ofono_gdbus_modem_get_interfaces: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Interfaces">"Interfaces"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_interfaces() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
ofono_gdbus_modem_get_interfaces (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_interfaces (object);
}

/**
 * ofono_gdbus_modem_dup_interfaces: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Interfaces">"Interfaces"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
ofono_gdbus_modem_dup_interfaces (OfonoGDBusModem *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "interfaces", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_interfaces: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Interfaces">"Interfaces"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_interfaces (OfonoGDBusModem *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "interfaces", value, NULL);
}

/**
 * ofono_gdbus_modem_get_type_: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets the value of the <link linkend="gdbus-property-org-ofono-Modem.Type">"Type"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use ofono_gdbus_modem_dup_type_() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
ofono_gdbus_modem_get_type_ (OfonoGDBusModem *object)
{
  return OFONO_GDBUS_MODEM_GET_IFACE (object)->get_type_ (object);
}

/**
 * ofono_gdbus_modem_dup_type_: (skip)
 * @object: A #OfonoGDBusModem.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-ofono-Modem.Type">"Type"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
ofono_gdbus_modem_dup_type_ (OfonoGDBusModem *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "type", &value, NULL);
  return value;
}

/**
 * ofono_gdbus_modem_set_type_: (skip)
 * @object: A #OfonoGDBusModem.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-ofono-Modem.Type">"Type"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
ofono_gdbus_modem_set_type_ (OfonoGDBusModem *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "type", value, NULL);
}

/**
 * ofono_gdbus_modem_emit_property_changed:
 * @object: A #OfonoGDBusModem.
 * @arg_name: Argument to pass with the signal.
 * @arg_value: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ofono-Modem.PropertyChanged">"PropertyChanged"</link> D-Bus signal.
 */
void
ofono_gdbus_modem_emit_property_changed (
    OfonoGDBusModem *object,
    const gchar *arg_name,
    GVariant *arg_value)
{
  g_signal_emit_by_name (object, "property-changed", arg_name, arg_value);
}

/**
 * ofono_gdbus_modem_call_get_properties:
 * @proxy: A #OfonoGDBusModemProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ofono-Modem.GetProperties">GetProperties()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_modem_call_get_properties_finish() to get the result of the operation.
 *
 * See ofono_gdbus_modem_call_get_properties_sync() for the synchronous, blocking version of this method.
 */
void
ofono_gdbus_modem_call_get_properties (
    OfonoGDBusModem *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetProperties",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ofono_gdbus_modem_call_get_properties_finish:
 * @proxy: A #OfonoGDBusModemProxy.
 * @out_properties: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_modem_call_get_properties().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ofono_gdbus_modem_call_get_properties().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_modem_call_get_properties_finish (
    OfonoGDBusModem *proxy,
    GVariant **out_properties,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_properties);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_modem_call_get_properties_sync:
 * @proxy: A #OfonoGDBusModemProxy.
 * @out_properties: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ofono-Modem.GetProperties">GetProperties()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_modem_call_get_properties() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_modem_call_get_properties_sync (
    OfonoGDBusModem *proxy,
    GVariant **out_properties,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetProperties",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_properties);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_modem_call_set_property:
 * @proxy: A #OfonoGDBusModemProxy.
 * @arg_property: Argument to pass with the method invocation.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ofono-Modem.SetProperty">SetProperty()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_modem_call_set_property_finish() to get the result of the operation.
 *
 * See ofono_gdbus_modem_call_set_property_sync() for the synchronous, blocking version of this method.
 */
void
ofono_gdbus_modem_call_set_property (
    OfonoGDBusModem *proxy,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetProperty",
    g_variant_new ("(s@v)",
                   arg_property,
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ofono_gdbus_modem_call_set_property_finish:
 * @proxy: A #OfonoGDBusModemProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_modem_call_set_property().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ofono_gdbus_modem_call_set_property().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_modem_call_set_property_finish (
    OfonoGDBusModem *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_modem_call_set_property_sync:
 * @proxy: A #OfonoGDBusModemProxy.
 * @arg_property: Argument to pass with the method invocation.
 * @arg_value: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ofono-Modem.SetProperty">SetProperty()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_modem_call_set_property() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_modem_call_set_property_sync (
    OfonoGDBusModem *proxy,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetProperty",
    g_variant_new ("(s@v)",
                   arg_property,
                   arg_value),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_modem_complete_get_properties:
 * @object: A #OfonoGDBusModem.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @properties: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ofono-Modem.GetProperties">GetProperties()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ofono_gdbus_modem_complete_get_properties (
    OfonoGDBusModem *object,
    GDBusMethodInvocation *invocation,
    GVariant *properties)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a{sv})",
                   properties));
}

/**
 * ofono_gdbus_modem_complete_set_property:
 * @object: A #OfonoGDBusModem.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ofono-Modem.SetProperty">SetProperty()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ofono_gdbus_modem_complete_set_property (
    OfonoGDBusModem *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * OfonoGDBusModemProxy:
 *
 * The #OfonoGDBusModemProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OfonoGDBusModemProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OfonoGDBusModemProxy.
 */

struct _OfonoGDBusModemProxyPrivate
{
  GData *qdata;
};

static void ofono_gdbus_modem_proxy_iface_init (OfonoGDBusModemIface *iface);

G_DEFINE_TYPE_WITH_CODE (OfonoGDBusModemProxy, ofono_gdbus_modem_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (OfonoGDBusModemProxy)
                         G_IMPLEMENT_INTERFACE (OFONO_GDBUS_TYPE_MODEM, ofono_gdbus_modem_proxy_iface_init));

static void
ofono_gdbus_modem_proxy_finalize (GObject *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (ofono_gdbus_modem_proxy_parent_class)->finalize (object);
}

static void
ofono_gdbus_modem_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 12);
  info = _ofono_gdbus_modem_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
ofono_gdbus_modem_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property '%s' on interface org.ofono.Modem: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
ofono_gdbus_modem_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 12);
  info = _ofono_gdbus_modem_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.ofono.Modem", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) ofono_gdbus_modem_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
ofono_gdbus_modem_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], OFONO_GDBUS_TYPE_MODEM);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, OFONO_GDBUS_TYPE_MODEM);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
ofono_gdbus_modem_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
ofono_gdbus_modem_proxy_get_powered (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Powered");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
ofono_gdbus_modem_proxy_get_online (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Online");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
ofono_gdbus_modem_proxy_get_lockdown (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Lockdown");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
ofono_gdbus_modem_proxy_get_emergency (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Emergency");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_name (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Name");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_manufacturer (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Manufacturer");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_model (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Model");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_revision (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Revision");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_serial (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Serial");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *const *
ofono_gdbus_modem_proxy_get_features (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  value = g_datalist_get_data (&proxy->priv->qdata, "Features");
  if (value != NULL)
    return value;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Features");
  if (variant != NULL)
    {
      value = g_variant_get_strv (variant, NULL);
      g_datalist_set_data_full (&proxy->priv->qdata, "Features", (gpointer) value, g_free);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *const *
ofono_gdbus_modem_proxy_get_interfaces (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  value = g_datalist_get_data (&proxy->priv->qdata, "Interfaces");
  if (value != NULL)
    return value;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Interfaces");
  if (variant != NULL)
    {
      value = g_variant_get_strv (variant, NULL);
      g_datalist_set_data_full (&proxy->priv->qdata, "Interfaces", (gpointer) value, g_free);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
ofono_gdbus_modem_proxy_get_type_ (OfonoGDBusModem *object)
{
  OfonoGDBusModemProxy *proxy = OFONO_GDBUS_MODEM_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Type");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
ofono_gdbus_modem_proxy_init (OfonoGDBusModemProxy *proxy)
{
  proxy->priv = ofono_gdbus_modem_proxy_get_instance_private (proxy);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), ofono_gdbus_modem_interface_info ());
}

static void
ofono_gdbus_modem_proxy_class_init (OfonoGDBusModemProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = ofono_gdbus_modem_proxy_finalize;
  gobject_class->get_property = ofono_gdbus_modem_proxy_get_property;
  gobject_class->set_property = ofono_gdbus_modem_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = ofono_gdbus_modem_proxy_g_signal;
  proxy_class->g_properties_changed = ofono_gdbus_modem_proxy_g_properties_changed;


  ofono_gdbus_modem_override_properties (gobject_class, 1);
}

static void
ofono_gdbus_modem_proxy_iface_init (OfonoGDBusModemIface *iface)
{
  iface->get_powered = ofono_gdbus_modem_proxy_get_powered;
  iface->get_online = ofono_gdbus_modem_proxy_get_online;
  iface->get_lockdown = ofono_gdbus_modem_proxy_get_lockdown;
  iface->get_emergency = ofono_gdbus_modem_proxy_get_emergency;
  iface->get_name = ofono_gdbus_modem_proxy_get_name;
  iface->get_manufacturer = ofono_gdbus_modem_proxy_get_manufacturer;
  iface->get_model = ofono_gdbus_modem_proxy_get_model;
  iface->get_revision = ofono_gdbus_modem_proxy_get_revision;
  iface->get_serial = ofono_gdbus_modem_proxy_get_serial;
  iface->get_features = ofono_gdbus_modem_proxy_get_features;
  iface->get_interfaces = ofono_gdbus_modem_proxy_get_interfaces;
  iface->get_type_ = ofono_gdbus_modem_proxy_get_type_;
}

/**
 * ofono_gdbus_modem_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_modem_proxy_new_finish() to get the result of the operation.
 *
 * See ofono_gdbus_modem_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
ofono_gdbus_modem_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (OFONO_GDBUS_TYPE_MODEM_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ofono.Modem", NULL);
}

/**
 * ofono_gdbus_modem_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_modem_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ofono_gdbus_modem_proxy_new().
 *
 * Returns: (transfer full) (type OfonoGDBusModemProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusModem *
ofono_gdbus_modem_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OFONO_GDBUS_MODEM (ret);
  else
    return NULL;
}

/**
 * ofono_gdbus_modem_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_modem_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OfonoGDBusModemProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusModem *
ofono_gdbus_modem_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (OFONO_GDBUS_TYPE_MODEM_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ofono.Modem", NULL);
  if (ret != NULL)
    return OFONO_GDBUS_MODEM (ret);
  else
    return NULL;
}


/**
 * ofono_gdbus_modem_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like ofono_gdbus_modem_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_modem_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See ofono_gdbus_modem_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
ofono_gdbus_modem_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (OFONO_GDBUS_TYPE_MODEM_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ofono.Modem", NULL);
}

/**
 * ofono_gdbus_modem_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_modem_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ofono_gdbus_modem_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type OfonoGDBusModemProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusModem *
ofono_gdbus_modem_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OFONO_GDBUS_MODEM (ret);
  else
    return NULL;
}

/**
 * ofono_gdbus_modem_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like ofono_gdbus_modem_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_modem_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OfonoGDBusModemProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusModem *
ofono_gdbus_modem_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (OFONO_GDBUS_TYPE_MODEM_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ofono.Modem", NULL);
  if (ret != NULL)
    return OFONO_GDBUS_MODEM (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * OfonoGDBusModemSkeleton:
 *
 * The #OfonoGDBusModemSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OfonoGDBusModemSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OfonoGDBusModemSkeleton.
 */

struct _OfonoGDBusModemSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_ofono_gdbus_modem_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], OFONO_GDBUS_TYPE_MODEM);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, OFONO_GDBUS_TYPE_MODEM);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_ofono_gdbus_modem_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_ofono_gdbus_modem_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_modem_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _ofono_gdbus_modem_skeleton_vtable =
{
  _ofono_gdbus_modem_skeleton_handle_method_call,
  _ofono_gdbus_modem_skeleton_handle_get_property,
  _ofono_gdbus_modem_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
ofono_gdbus_modem_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return ofono_gdbus_modem_interface_info ();
}

static GDBusInterfaceVTable *
ofono_gdbus_modem_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_ofono_gdbus_modem_skeleton_vtable;
}

static GVariant *
ofono_gdbus_modem_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_ofono_gdbus_modem_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _ofono_gdbus_modem_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _ofono_gdbus_modem_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _ofono_gdbus_modem_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ofono.Modem", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _ofono_gdbus_modem_emit_changed (gpointer user_data);

static void
ofono_gdbus_modem_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _ofono_gdbus_modem_emit_changed (skeleton);
}

static void
_ofono_gdbus_modem_on_signal_property_changed (
    OfonoGDBusModem *object,
    const gchar *arg_name,
    GVariant *arg_value)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s@v)",
                   arg_name,
                   arg_value));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ofono.Modem", "PropertyChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void ofono_gdbus_modem_skeleton_iface_init (OfonoGDBusModemIface *iface);
G_DEFINE_TYPE_WITH_CODE (OfonoGDBusModemSkeleton, ofono_gdbus_modem_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (OfonoGDBusModemSkeleton)
                         G_IMPLEMENT_INTERFACE (OFONO_GDBUS_TYPE_MODEM, ofono_gdbus_modem_skeleton_iface_init));

static void
ofono_gdbus_modem_skeleton_finalize (GObject *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  guint n;
  for (n = 0; n < 12; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (ofono_gdbus_modem_skeleton_parent_class)->finalize (object);
}

static void
ofono_gdbus_modem_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 12);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_ofono_gdbus_modem_emit_changed (gpointer user_data)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.ofono.Modem",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_ofono_gdbus_modem_schedule_emit_changed (OfonoGDBusModemSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
ofono_gdbus_modem_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _ofono_gdbus_modem_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
ofono_gdbus_modem_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 12);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _ofono_gdbus_modem_schedule_emit_changed (skeleton, _ofono_gdbus_modem_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
ofono_gdbus_modem_skeleton_init (OfonoGDBusModemSkeleton *skeleton)
{
  skeleton->priv = ofono_gdbus_modem_skeleton_get_instance_private (skeleton);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 12);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[4], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[5], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[6], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[7], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[8], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[9], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[10], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[11], G_TYPE_STRING);
}

static gboolean 
ofono_gdbus_modem_skeleton_get_powered (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
ofono_gdbus_modem_skeleton_get_online (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
ofono_gdbus_modem_skeleton_get_lockdown (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
ofono_gdbus_modem_skeleton_get_emergency (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_name (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[4]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_manufacturer (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[5]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_model (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[6]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_revision (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[7]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_serial (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[8]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *const *
ofono_gdbus_modem_skeleton_get_features (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boxed (&(skeleton->priv->properties[9]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *const *
ofono_gdbus_modem_skeleton_get_interfaces (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boxed (&(skeleton->priv->properties[10]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
ofono_gdbus_modem_skeleton_get_type_ (OfonoGDBusModem *object)
{
  OfonoGDBusModemSkeleton *skeleton = OFONO_GDBUS_MODEM_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[11]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
ofono_gdbus_modem_skeleton_class_init (OfonoGDBusModemSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = ofono_gdbus_modem_skeleton_finalize;
  gobject_class->get_property = ofono_gdbus_modem_skeleton_get_property;
  gobject_class->set_property = ofono_gdbus_modem_skeleton_set_property;
  gobject_class->notify       = ofono_gdbus_modem_skeleton_notify;


  ofono_gdbus_modem_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = ofono_gdbus_modem_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = ofono_gdbus_modem_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = ofono_gdbus_modem_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = ofono_gdbus_modem_skeleton_dbus_interface_get_vtable;
}

static void
ofono_gdbus_modem_skeleton_iface_init (OfonoGDBusModemIface *iface)
{
  iface->property_changed = _ofono_gdbus_modem_on_signal_property_changed;
  iface->get_powered = ofono_gdbus_modem_skeleton_get_powered;
  iface->get_online = ofono_gdbus_modem_skeleton_get_online;
  iface->get_lockdown = ofono_gdbus_modem_skeleton_get_lockdown;
  iface->get_emergency = ofono_gdbus_modem_skeleton_get_emergency;
  iface->get_name = ofono_gdbus_modem_skeleton_get_name;
  iface->get_manufacturer = ofono_gdbus_modem_skeleton_get_manufacturer;
  iface->get_model = ofono_gdbus_modem_skeleton_get_model;
  iface->get_revision = ofono_gdbus_modem_skeleton_get_revision;
  iface->get_serial = ofono_gdbus_modem_skeleton_get_serial;
  iface->get_features = ofono_gdbus_modem_skeleton_get_features;
  iface->get_interfaces = ofono_gdbus_modem_skeleton_get_interfaces;
  iface->get_type_ = ofono_gdbus_modem_skeleton_get_type_;
}

/**
 * ofono_gdbus_modem_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Modem.top_of_page">org.ofono.Modem</link>.
 *
 * Returns: (transfer full) (type OfonoGDBusModemSkeleton): The skeleton object.
 */
OfonoGDBusModem *
ofono_gdbus_modem_skeleton_new (void)
{
  return OFONO_GDBUS_MODEM (g_object_new (OFONO_GDBUS_TYPE_MODEM_SKELETON, NULL));
}

