/*
 * Generated by gdbus-codegen 2.38.1. DO NOT EDIT.
 *
 *   gdbus-codegen --interface-prefix org.ofono. \
 *                 --generate-c-code gdbusmanager \
 *                 --c-namespace OfonoGDBus \
 *                 org.ofono.Manager.xml
 *
 * The license of this code is the same as for the source it was derived from.
 */

#include "mozilla/dom/ofono/gdbusmanager.h"

#include <string.h>

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.ofono.Manager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:OfonoGDBusManager
 * @title: OfonoGDBusManager
 * @short_description: Generated C code for the org.ofono.Manager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.ofono.Manager ---- */

static const _ExtendedGDBusArgInfo _ofono_gdbus_manager_method_info_get_modems_OUT_ARG_modems =
{
  {
    -1,
    (gchar *) "modems",
    (gchar *) "a(oa{sv})",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_manager_method_info_get_modems_OUT_ARG_pointers[] =
{
  &_ofono_gdbus_manager_method_info_get_modems_OUT_ARG_modems,
  NULL
};

static const _ExtendedGDBusMethodInfo _ofono_gdbus_manager_method_info_get_modems =
{
  {
    -1,
    (gchar *) "GetModems",
    NULL,
    (GDBusArgInfo **) &_ofono_gdbus_manager_method_info_get_modems_OUT_ARG_pointers,
    NULL
  },
  "handle-get-modems",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _ofono_gdbus_manager_method_info_pointers[] =
{
  &_ofono_gdbus_manager_method_info_get_modems,
  NULL
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_manager_signal_info_modem_added_ARG_path =
{
  {
    -1,
    (gchar *) "path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_manager_signal_info_modem_added_ARG_properties =
{
  {
    -1,
    (gchar *) "properties",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_manager_signal_info_modem_added_ARG_pointers[] =
{
  &_ofono_gdbus_manager_signal_info_modem_added_ARG_path,
  &_ofono_gdbus_manager_signal_info_modem_added_ARG_properties,
  NULL
};

static const _ExtendedGDBusSignalInfo _ofono_gdbus_manager_signal_info_modem_added =
{
  {
    -1,
    (gchar *) "ModemAdded",
    (GDBusArgInfo **) &_ofono_gdbus_manager_signal_info_modem_added_ARG_pointers,
    NULL
  },
  "modem-added"
};

static const _ExtendedGDBusArgInfo _ofono_gdbus_manager_signal_info_modem_removed_ARG_path =
{
  {
    -1,
    (gchar *) "path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ofono_gdbus_manager_signal_info_modem_removed_ARG_pointers[] =
{
  &_ofono_gdbus_manager_signal_info_modem_removed_ARG_path,
  NULL
};

static const _ExtendedGDBusSignalInfo _ofono_gdbus_manager_signal_info_modem_removed =
{
  {
    -1,
    (gchar *) "ModemRemoved",
    (GDBusArgInfo **) &_ofono_gdbus_manager_signal_info_modem_removed_ARG_pointers,
    NULL
  },
  "modem-removed"
};

static const _ExtendedGDBusSignalInfo * const _ofono_gdbus_manager_signal_info_pointers[] =
{
  &_ofono_gdbus_manager_signal_info_modem_added,
  &_ofono_gdbus_manager_signal_info_modem_removed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _ofono_gdbus_manager_interface_info =
{
  {
    -1,
    (gchar *) "org.ofono.Manager",
    (GDBusMethodInfo **) &_ofono_gdbus_manager_method_info_pointers,
    (GDBusSignalInfo **) &_ofono_gdbus_manager_signal_info_pointers,
    NULL,
    NULL
  },
  "manager",
};


/**
 * ofono_gdbus_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
ofono_gdbus_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_ofono_gdbus_manager_interface_info.parent_struct;
}

/**
 * ofono_gdbus_manager_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #OfonoGDBusManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
ofono_gdbus_manager_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * OfonoGDBusManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link>.
 */

/**
 * OfonoGDBusManagerIface:
 * @parent_iface: The parent interface.
 * @handle_get_modems: Handler for the #OfonoGDBusManager::handle-get-modems signal.
 * @modem_added: Handler for the #OfonoGDBusManager::modem-added signal.
 * @modem_removed: Handler for the #OfonoGDBusManager::modem-removed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link>.
 */

typedef OfonoGDBusManagerIface OfonoGDBusManagerInterface;
G_DEFINE_INTERFACE (OfonoGDBusManager, ofono_gdbus_manager, G_TYPE_OBJECT);

static void
ofono_gdbus_manager_default_init (OfonoGDBusManagerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * OfonoGDBusManager::handle-get-modems:
   * @object: A #OfonoGDBusManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ofono-Manager.GetModems">GetModems()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ofono_gdbus_manager_complete_get_modems() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-modems",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusManagerIface, handle_get_modems),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject signals for received D-Bus signals: */
  /**
   * OfonoGDBusManager::modem-added:
   * @object: A #OfonoGDBusManager.
   * @arg_path: Argument.
   * @arg_properties: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ofono-Manager.ModemAdded">"ModemAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("modem-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusManagerIface, modem_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * OfonoGDBusManager::modem-removed:
   * @object: A #OfonoGDBusManager.
   * @arg_path: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ofono-Manager.ModemRemoved">"ModemRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("modem-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OfonoGDBusManagerIface, modem_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

}

/**
 * ofono_gdbus_manager_emit_modem_added:
 * @object: A #OfonoGDBusManager.
 * @arg_path: Argument to pass with the signal.
 * @arg_properties: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ofono-Manager.ModemAdded">"ModemAdded"</link> D-Bus signal.
 */
void
ofono_gdbus_manager_emit_modem_added (
    OfonoGDBusManager *object,
    const gchar *arg_path,
    GVariant *arg_properties)
{
  g_signal_emit_by_name (object, "modem-added", arg_path, arg_properties);
}

/**
 * ofono_gdbus_manager_emit_modem_removed:
 * @object: A #OfonoGDBusManager.
 * @arg_path: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ofono-Manager.ModemRemoved">"ModemRemoved"</link> D-Bus signal.
 */
void
ofono_gdbus_manager_emit_modem_removed (
    OfonoGDBusManager *object,
    const gchar *arg_path)
{
  g_signal_emit_by_name (object, "modem-removed", arg_path);
}

/**
 * ofono_gdbus_manager_call_get_modems:
 * @proxy: A #OfonoGDBusManagerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ofono-Manager.GetModems">GetModems()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_manager_call_get_modems_finish() to get the result of the operation.
 *
 * See ofono_gdbus_manager_call_get_modems_sync() for the synchronous, blocking version of this method.
 */
void
ofono_gdbus_manager_call_get_modems (
    OfonoGDBusManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetModems",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ofono_gdbus_manager_call_get_modems_finish:
 * @proxy: A #OfonoGDBusManagerProxy.
 * @out_modems: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_manager_call_get_modems().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ofono_gdbus_manager_call_get_modems().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_manager_call_get_modems_finish (
    OfonoGDBusManager *proxy,
    GVariant **out_modems,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(oa{sv}))",
                 out_modems);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_manager_call_get_modems_sync:
 * @proxy: A #OfonoGDBusManagerProxy.
 * @out_modems: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ofono-Manager.GetModems">GetModems()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_manager_call_get_modems() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ofono_gdbus_manager_call_get_modems_sync (
    OfonoGDBusManager *proxy,
    GVariant **out_modems,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetModems",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(oa{sv}))",
                 out_modems);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ofono_gdbus_manager_complete_get_modems:
 * @object: A #OfonoGDBusManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @modems: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ofono-Manager.GetModems">GetModems()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ofono_gdbus_manager_complete_get_modems (
    OfonoGDBusManager *object,
    GDBusMethodInvocation *invocation,
    GVariant *modems)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(oa{sv}))",
                   modems));
}

/* ------------------------------------------------------------------------ */

/**
 * OfonoGDBusManagerProxy:
 *
 * The #OfonoGDBusManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OfonoGDBusManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OfonoGDBusManagerProxy.
 */

struct _OfonoGDBusManagerProxyPrivate
{
  GData *qdata;
};

static void ofono_gdbus_manager_proxy_iface_init (OfonoGDBusManagerIface *iface);

G_DEFINE_TYPE_WITH_CODE (OfonoGDBusManagerProxy, ofono_gdbus_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (OfonoGDBusManagerProxy)
                         G_IMPLEMENT_INTERFACE (OFONO_GDBUS_TYPE_MANAGER, ofono_gdbus_manager_proxy_iface_init));

static void
ofono_gdbus_manager_proxy_finalize (GObject *object)
{
  OfonoGDBusManagerProxy *proxy = OFONO_GDBUS_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (ofono_gdbus_manager_proxy_parent_class)->finalize (object);
}

static void
ofono_gdbus_manager_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
ofono_gdbus_manager_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
ofono_gdbus_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_ofono_gdbus_manager_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], OFONO_GDBUS_TYPE_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, OFONO_GDBUS_TYPE_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
ofono_gdbus_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  OfonoGDBusManagerProxy *proxy = OFONO_GDBUS_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_manager_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ofono_gdbus_manager_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
ofono_gdbus_manager_proxy_init (OfonoGDBusManagerProxy *proxy)
{
  proxy->priv = ofono_gdbus_manager_proxy_get_instance_private (proxy);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), ofono_gdbus_manager_interface_info ());
}

static void
ofono_gdbus_manager_proxy_class_init (OfonoGDBusManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = ofono_gdbus_manager_proxy_finalize;
  gobject_class->get_property = ofono_gdbus_manager_proxy_get_property;
  gobject_class->set_property = ofono_gdbus_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = ofono_gdbus_manager_proxy_g_signal;
  proxy_class->g_properties_changed = ofono_gdbus_manager_proxy_g_properties_changed;

}

static void
ofono_gdbus_manager_proxy_iface_init (OfonoGDBusManagerIface *iface)
{
}

/**
 * ofono_gdbus_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_manager_proxy_new_finish() to get the result of the operation.
 *
 * See ofono_gdbus_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
ofono_gdbus_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (OFONO_GDBUS_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ofono.Manager", NULL);
}

/**
 * ofono_gdbus_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ofono_gdbus_manager_proxy_new().
 *
 * Returns: (transfer full) (type OfonoGDBusManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusManager *
ofono_gdbus_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OFONO_GDBUS_MANAGER (ret);
  else
    return NULL;
}

/**
 * ofono_gdbus_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ofono-Manager.top_of_page">org.ofono.Manager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OfonoGDBusManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusManager *
ofono_gdbus_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (OFONO_GDBUS_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ofono.Manager", NULL);
  if (ret != NULL)
    return OFONO_GDBUS_MANAGER (ret);
  else
    return NULL;
}


/**
 * ofono_gdbus_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like ofono_gdbus_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ofono_gdbus_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See ofono_gdbus_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
ofono_gdbus_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (OFONO_GDBUS_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ofono.Manager", NULL);
}

/**
 * ofono_gdbus_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ofono_gdbus_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ofono_gdbus_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type OfonoGDBusManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusManager *
ofono_gdbus_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OFONO_GDBUS_MANAGER (ret);
  else
    return NULL;
}

/**
 * ofono_gdbus_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like ofono_gdbus_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ofono_gdbus_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OfonoGDBusManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OfonoGDBusManager *
ofono_gdbus_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (OFONO_GDBUS_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ofono.Manager", NULL);
  if (ret != NULL)
    return OFONO_GDBUS_MANAGER (ret);
  else
    return NULL;
}

