/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(4225c8c2-3471-407d-8294-ebbfe7267bba)]
interface nsIVoicemailListener : nsISupports
{
  /**
   * Called when a voicemail notification has been received by the network.
   */
  void notifyStatusChanged(in boolean hasMessages,
                           in long messageCount,
                           in DOMString returnNumber,
                           in DOMString returnMessage);
};

/**
 * XPCOM component (in the content process) that provides the voicemail
 * information.
 */
[scriptable, uuid(93e125b2-68c3-4fa4-8343-25bc130a732c)]
interface nsIVoicemailProvider : nsISupports
{
  /**
   * Called when a content process registers receiving unsolicited messages from
   * RadioInterfaceLayer in the chrome process. Only a content process that has
   * the 'voicemail' permission is allowed to register.
   */
  void registerVoicemailMsg(in nsIVoicemailListener listener);
  void unregisterVoicemailMsg(in nsIVoicemailListener listener);

  readonly attribute DOMString voicemailNumber;
  readonly attribute DOMString voicemailDisplayName;
};
