/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this file,
* You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsINetworkInterface;

[scriptable, function, uuid(e7de41f5-0e49-441b-897d-6e85c0dae045)]
interface nsINetworkStatsServiceCallback : nsISupports
{
  /*
   * @param aResult callback result with boolean value
   * @param aMessage message
   */
  void notify(in boolean aResult, in jsval aMessage);
};

[scriptable, uuid(8077efb2-4c98-4e82-868e-45b62c1a9cd9)]
interface nsINetworkStatsService : nsISupports
{
  /*
   * An interface used to record per-app traffic data.
   * @param aAppId app id
   * @param aNetworkInterface network
   * @param aTimeStamp time stamp
   * @param aRxBytes received data amount
   * @param aTxBytes transmitted data amount
   * @param aIsAccumulative is stats accumulative
   * @param aCallback an optional callback
   */
  void saveAppStats(in unsigned long aAppId,
                    in nsINetworkInterface aNetwork,
                    in unsigned long long aTimeStamp,
                    in unsigned long long aRxBytes,
                    in unsigned long long aTxBytes,
                    in boolean aIsAccumulative,
         [optional] in nsINetworkStatsServiceCallback aCallback);
};
