/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * XPCOM component (in the content process) that provides the cell broadcast
 * information.
 */
[scriptable, uuid(6a25f5dc-60ff-4937-9043-33225cf7d483)]
interface nsICellBroadcastService : nsISupports
{
  /**
   * Called when a content process registers receiving unsolicited messages from
   * RadioInterfaceLayer in the chrome process. Only a content process that has
   * the 'cellbroadcast' permission is allowed to register.
   */
  void registerCellBroadcastMsg();
};
